"""empty message

Revision ID: 68518a4e66a8
Revises: 
Create Date: 2022-06-24 13:18:30.044445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68518a4e66a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'numbers_of_pets')
    op.add_column('pet', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'count')
    op.add_column('cart', sa.Column('numbers_of_pets', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
