"""empty message

Revision ID: 866f486d2517
Revises: fb1de25f3eea
Create Date: 2022-06-22 22:55:45.147945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866f486d2517'
down_revision = 'fb1de25f3eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('cart', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'cart')
    # ### end Alembic commands ###
