"""empty message

Revision ID: 11944f1c4c53
Revises: 986a82ba3c24
Create Date: 2022-06-25 22:35:04.340085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11944f1c4c53'
down_revision = '986a82ba3c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
