"""empty message

Revision ID: 986a82ba3c24
Revises: e23678ff4a4a
Create Date: 2022-06-25 22:32:13.299881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986a82ba3c24'
down_revision = 'e23678ff4a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
