"""empty message

Revision ID: 30c61f7981e7
Revises: 
Create Date: 2022-07-07 19:24:50.813727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c61f7981e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrency',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('first_historical_data', sa.String(), nullable=False),
    sa.Column('last_historical_data', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypto',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crypto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto')
    op.drop_table('user')
    op.drop_table('cryptocurrency')
    # ### end Alembic commands ###
